[package]
name = "fwupdater-mobile"
version = "0.1.0"
edition = "2021"

[lib]
name = "fwupdater_mobile"
crate-type = ["cdylib", "staticlib", "lib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["uniffi/cli"]

[dependencies]
fwupdater-core = { path = "../fwupdater-core" }
thiserror = "1"

[dependencies.uniffi]
version = "0.29"
